### PR TITLE
CIF-1206 - [Github #88] Connector caches MUST include the store view header value

### LINKED ISSUE #87: Disable cache for "CIF Catalog Magento GraphQL Configuration Factory" doesn't work
### Expected Behaviour

When cache is disabled, that the CIF Virtual catalog & Product Console is still working.
I am doing tests in Magento and want to see them reflected faster in AEM. Therefore, locally I want to disable cache. 

I could only bypass caching, by configuring all values to in the CIF Catalog Magento GraphQL Configuration Factory OSGI config to "1".

### Actual Behaviour

When any of these checkboxes is disabled, the Product Console is not working anymore.

Schermafbeelding 2020-01-24 om 07 08 57
(after changing this config, I had to restart the CIF Connector Bundle)

No categories or products will load anymore on this screen:
http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products

### Reproduce Scenario (including but not limited to)

1. Disable on, some or all checkboxes for caching on the "CIF Catalog Magento GraphQL Configuration Factory" OSGI config
2. Restart the CIF Connector & CIF Virtual catalog bundle
3. Go to http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products
4. Try to open a virtual catalog pointing to Magento

I need to mention that I have a Product binding for multiple StoreViews on a single Magento instance (also have 1 OSGI config for this environment, and I am re-using the "Project" on the Product Bind config.

#### Platform and Version
AEM 6.4.5
CIF Connector 0.7.1

### LINKED ISSUE #88: Multiple Product Bindings, pointing to same Magento don't load products correctly
### Expected Behaviour

When having multiple Product Bindings (1 per StoreView), using the same project (so same Magento) and caching is enabled, each Product Binding should load the correct catalog.

### Actual Behaviour

When having multiple Product Bindings (1 per StoreView), using the same project (so same Magento), caching is enabled (to 5 minutes & 1000 items), the categories load correctly and show the category translations for that StoreView. 

Schermafbeelding 2020-01-24 om 07 19 50

But the products loaded for each category are the products of the first StoreView that I selected. When clicking the next Product Binding, I am seeing the same products, knowing other products should be visible. After cache expiration, the first Product Binding I select and showed the products for, these will be the products that are used for the other Product Bindings.

Schermafbeelding 2020-01-24 om 07 26 57
(I first opened the French Product Binding, all French products for all Store Views)

Schermafbeelding 2020-01-24 om 07 30 04
(This time I opened the US Product Binding, all products for US are shows for all Store Views)

In Magento 1 have 3 StoreViews, on a global level I created 2 categories and on a global level I added products for 3 StoreViews. In Magento, when switching to the specific StoreViews, I could see which products would be loaded per StoreView, but not all should be visible on all Store Views. I have SKUs that are only applicable to some locales/StoreViews.

#### Steps to Reproduce

1. http://localhost:4502/libs/commerce/gui/content/products.html/var/commerce/products/
2. Make sure you have 2 or 3 Product Bindings, all pointing to the same Magento OSGI config, but each loading a different StoreView
3. In Magento, populate the categories with products, knowing different products will be visible on different StoreViews. Also translate the categories per StoreView
4. Make sure cache is enabled on the OSGI config
5. Now navigate through the categories until you see products
6. Go to another Product Binding (for another StoreView for the same Magento), you will see the category names are translated, but the products of the first selected Product Binding are used.

#### Platform and Version
AEM 6.4.5
CIF Connector 0.7.1
Magento 2.3.1 (Could this be related to this version of Magento? Planning to upgrade soon)

### PR DESCRIPTION
**Pull request by cjelger**
## Related Issues

Fixes #88 and fixes #87 

## How Has This Been Tested?

Extended unit tests and tested locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

File: bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java [hunk 1]
```diff
@@ -159,13 +157,14 @@ public ProductInterface getProductBySku(String sku, String storeView) {
         }
 
         try {
-            return productCache.get(sku, () -> getProductBySkuImpl(sku, storeView)).orElse(null);
+            String key = sku + StringUtils.defaultString(storeView, MAGENTO_DEFAULT_STORE);
```
Comment (herzog31) [inline bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java]: It would be better to use a separator when generating the key. Otherwise duplicate keys because of overlaps in the sku and storeview might occur.

Comment (cjelger) [reply bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java]: I generated all cache keys with the same method so it's kind of unified and now used a separator that is less likely (than `-`) to appear in skus and store views but ... this doesn't prevent collisions, it just makes them less likely to occur. Consider the following cases:

```
   SKU        STORE      SEPARATOR     CACHE KEY

sku|        store|view      ''       sku|store|view
sku|store   |view           ''       sku|store|view
sku         store|view      '|'      sku|store|view
sku|store   view            '|'      sku|store|view
```
They all generate the same keys, so using a separator doesn't really help. However I think the `|` character wouldn't be common in skus and store views, so I think we can consider the collision probability very low.

**Review by herzog31 — APPROVED** [review]

File: bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java (hunk 1 above)
Comment (cjelger) [reply bundles/cif-connector-graphql/src/main/java/com/adobe/cq/commerce/graphql/magento/GraphqlDataServiceImpl.java]: @herzog31 I finally decided to replace the string keys with a dedicated class to use an array as a key, so we completely remove the issue with strings.

**Review by mhaack — APPROVED** [review]

**Review by dplaton — APPROVED** [review]
