### PR TITLE
CIF-2082 - Use of CatalogDataResourceProviderManager and how to combine with product nodes

### LINKED ISSUE #173: Use of CatalogDataResourceProviderManager and how to combine with product nodes
### Expected Behaviour

In our set-up we have the CIF connector installed and use Product bindings in /var/commerce/products to virtually connect to Magento. No nodes will ever be created for the Magento use case under /var/commerce/products/our-magento-binding/.

But we also have a brand that wants to use the traditional way of handling products by importing products under /var/commerce/products/traditional-imported-products/.

### Actual Behaviour

When updating, creating or removing a node in /var/commerce/products/traditional-imported-products/, we see the following stack trace in the log files and the system becomes very slow due to huge amount of data.

07.05.2021 15:04:42.733 *WARN* [sling-oak-observation-10] org.apache.jackrabbit.oak.plugins.index.lucene.LucenePropertyIndex Index-Traversed 20000 nodes with filter Filter(query=SELECT * FROM [sling:Folder] WHERE ISDESCENDANTNODE('/var/commerce/products') AND [sling:Folder].'cq:catalogDataResourceProviderFactory' IS NOT NULL, path=/var/commerce/products//*, property=[cq:catalogDataResourceProviderFactory=[is not null]])

We also are wondering what this class is exactly doing: https://github.com/adobe/commerce-cif-connector/blob/7d56aa839ef646edb8d47e4fe1ead91d97349182/bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java
(this is the class causing the log file entries)
Why is this needed for the Magento integration and shouldn't it be configured differently to only be triggered for the Magento bindings only?

#### Steps to Reproduce

Create a traditional folder under /var/commerce/products
and create product nodes.

#### Platform and Version

CIF 0.9.0, AEM 6.4.5

#### Logs taken while reproducing problem

07.05.2021 15:04:42.733 *WARN* [sling-oak-observation-10] org.apache.jackrabbit.oak.plugins.index.lucene.LucenePropertyIndex Index-Traversed 20000 nodes with filter Filter(query=SELECT * FROM [sling:Folder] WHERE ISDESCENDANTNODE('/var/commerce/products') AND [sling:Folder].'cq:catalogDataResourceProviderFactory' IS NOT NULL, path=/var/commerce/products//*, property=[cq:catalogDataResourceProviderFactory=[is not null]])

### PR DESCRIPTION
**Pull request by LSantha**
Avoid calling CatalogDataResourceProviderManagerImpl.findDataRoots() when non binding related nodes are created in /var/commerce/products.
 Added unit test.

## Related Issue

CIF-2082

## How Has This Been Tested?

Manually, unit tests.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

File: bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java [hunk 1]
```diff
@@ -102,7 +102,7 @@
 
     private EventListener[] observationEventListeners;
 
-    private volatile List<Resource> dataRoots;
+    private final List<Resource> dataRoots = Collections.synchronizedList(new ArrayList<>());
```
Comment (buuhuu) [inline bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java]: You could use a CopyOnWriteArrayList instead as I think for this usecase read operations outnumber mutations, right?

File: bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java [hunk 2]
```diff
@@ -478,11 +489,15 @@ void unbindFactory(CatalogDataResourceProviderFactory factory, Map<String, Strin
 
     @Override
     public List<Resource> getDataRoots() {
-        return dataRoots != null ? dataRoots : findDataRoots(resolver);
+        List<Resource> roots = new ArrayList<>();
+        synchronized (dataRoots) {
```
Comment (buuhuu) [inline bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java]: When using a CopyOnWirteArrayList you don't need synchronisation here. I assume this is more often called than  registerDataRoot(s) and so synchronisation would have a negative impact.

File: bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java [hunk 3]
```diff
@@ -174,8 +173,10 @@
...
         }
-        dataRoots = allResources;
-        return allResources;
+        synchronized (dataRoots) {
+            dataRoots.clear();
+            dataRoots.addAll(allResources);
+        }
     }
 
     private void registerDataRoots() {
```
Comment (buuhuu) [inline bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java:185]: Instead of the fine-granular concurrent access control, I think its is easier to just make the registerDataRoots() and registerDataRoot() synchronised.

File: bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java (hunk 1 above)
Comment (LSantha) [reply bundles/cif-virtual-catalog/src/main/java/com/adobe/cq/commerce/virtual/catalog/data/impl/CatalogDataResourceProviderManagerImpl.java]: Indeed, CopyOnWriteArrayList looks like a good fit here. I've changed that.

**Review by herzog31 — APPROVED** [review]

**Comment by mhaack** [comment]
I think we also need to backport this to 0.9.0 branch. @geertsmichael wrote in #173 they still use 0.9.0 version.
